# Generated by Django 3.2.8 on 2021-11-05 01:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tintuc', '0002_alter_baiviet_ngaydangbaiviet'),
    ]

    operations = [
        migrations.CreateModel(
            name='Covid',
            fields=[
                ('idcovid', models.AutoField(primary_key=True, serialize=False)),
                ('tongsoca', models.IntegerField(blank=True, null=True)),
                ('homnay', models.IntegerField(blank=True, null=True)),
                ('tuvong', models.IntegerField(blank=True, null=True)),
                ('ngaycapnhatcovid', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'covid',
            },
        ),
        migrations.CreateModel(
            name='Yenbaivacine',
            fields=[
                ('idvaccine', models.AutoField(primary_key=True, serialize=False)),
                ('khphanbo', models.IntegerField(blank=True, null=True)),
                ('phanbothucte', models.IntegerField(blank=True, null=True)),
                ('danso', models.IntegerField(blank=True, null=True)),
                ('solieudatiem', models.IntegerField(blank=True, null=True)),
                ('ngaycapnhat', models.ForeignKey(blank=True, db_column='ngaycapnhat', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tintuc.ngaythang')),
            ],
            options={
                'db_table': 'yenbaivacine',
            },
        ),
        migrations.CreateModel(
            name='Yenbaicovid',
            fields=[
                ('idcovid', models.AutoField(primary_key=True, serialize=False)),
                ('tongsoca', models.IntegerField(blank=True, null=True)),
                ('homnay', models.IntegerField(blank=True, null=True)),
                ('tuvong', models.IntegerField(blank=True, null=True)),
                ('ngaycapnhatcovid', models.ForeignKey(blank=True, db_column='ngaycapnhatcovid', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tintuc.ngaythang')),
            ],
            options={
                'db_table': 'yenbaicovid',
            },
        ),
        migrations.CreateModel(
            name='Vinhphucvacine',
            fields=[
                ('idvaccine', models.AutoField(primary_key=True, serialize=False)),
                ('khphanbo', models.IntegerField(blank=True, null=True)),
                ('phanbothucte', models.IntegerField(blank=True, null=True)),
                ('danso', models.IntegerField(blank=True, null=True)),
                ('solieudatiem', models.IntegerField(blank=True, null=True)),
                ('ngaycapnhat', models.ForeignKey(blank=True, db_column='ngaycapnhat', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tintuc.ngaythang')),
            ],
            options={
                'db_table': 'vinhphucvacine',
            },
        ),
        migrations.CreateModel(
            name='Vinhphuccovid',
            fields=[
                ('idcovid', models.AutoField(primary_key=True, serialize=False)),
                ('tongsoca', models.IntegerField(blank=True, null=True)),
                ('homnay', models.IntegerField(blank=True, null=True)),
                ('tuvong', models.IntegerField(blank=True, null=True)),
                ('ngaycapnhatcovid', models.ForeignKey(blank=True, db_column='ngaycapnhatcovid', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tintuc.ngaythang')),
            ],
            options={
                'db_table': 'vinhphuccovid',
            },
        ),
        migrations.CreateModel(
            name='Vinhlongvacine',
            fields=[
                ('idvaccine', models.AutoField(primary_key=True, serialize=False)),
                ('khphanbo', models.IntegerField(blank=True, null=True)),
                ('phanbothucte', models.IntegerField(blank=True, null=True)),
                ('danso', models.IntegerField(blank=True, null=True)),
                ('solieudatiem', models.IntegerField(blank=True, null=True)),
                ('ngaycapnhat', models.ForeignKey(blank=True, db_column='ngaycapnhat', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tintuc.ngaythang')),
            ],
            options={
                'db_table': 'vinhlongvacine',
            },
        ),
        migrations.CreateModel(
            name='Vinhlongcovid',
            fields=[
                ('idcovid', models.AutoField(primary_key=True, serialize=False)),
                ('tongsoca', models.IntegerField(blank=True, null=True)),
                ('homnay', models.IntegerField(blank=True, null=True)),
                ('tuvong', models.IntegerField(blank=True, null=True)),
                ('ngaycapnhatcovid', models.ForeignKey(blank=True, db_column='ngaycapnhatcovid', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tintuc.ngaythang')),
            ],
            options={
                'db_table': 'vinhlongcovid',
            },
        ),
        migrations.CreateModel(
            name='Tuyenquangvacine',
            fields=[
                ('idvaccine', models.AutoField(primary_key=True, serialize=False)),
                ('khphanbo', models.IntegerField(blank=True, null=True)),
                ('phanbothucte', models.IntegerField(blank=True, null=True)),
                ('danso', models.IntegerField(blank=True, null=True)),
                ('solieudatiem', models.IntegerField(blank=True, null=True)),
                ('ngaycapnhat', models.ForeignKey(blank=True, db_column='ngaycapnhat', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tintuc.ngaythang')),
            ],
            options={
                'db_table': 'tuyenquangvacine',
            },
        ),
        migrations.CreateModel(
            name='Tuyenquangcovid',
            fields=[
                ('idcovid', models.AutoField(primary_key=True, serialize=False)),
                ('tongsoca', models.IntegerField(blank=True, null=True)),
                ('homnay', models.IntegerField(blank=True, null=True)),
                ('tuvong', models.IntegerField(blank=True, null=True)),
                ('ngaycapnhatcovid', models.ForeignKey(blank=True, db_column='ngaycapnhatcovid', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tintuc.ngaythang')),
            ],
            options={
                'db_table': 'tuyenquangcovid',
            },
        ),
        migrations.CreateModel(
            name='Travinhvacine',
            fields=[
                ('idvaccine', models.AutoField(primary_key=True, serialize=False)),
                ('khphanbo', models.IntegerField(blank=True, null=True)),
                ('phanbothucte', models.IntegerField(blank=True, null=True)),
                ('danso', models.IntegerField(blank=True, null=True)),
                ('solieudatiem', models.IntegerField(blank=True, null=True)),
                ('ngaycapnhat', models.ForeignKey(blank=True, db_column='ngaycapnhat', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tintuc.ngaythang')),
            ],
            options={
                'db_table': 'travinhvacine',
            },
        ),
        migrations.CreateModel(
            name='Travinhcovid',
            fields=[
                ('idcovid', models.AutoField(primary_key=True, serialize=False)),
                ('tongsoca', models.IntegerField(blank=True, null=True)),
                ('homnay', models.IntegerField(blank=True, null=True)),
                ('tuvong', models.IntegerField(blank=True, null=True)),
                ('ngaycapnhatcovid', models.ForeignKey(blank=True, db_column='ngaycapnhatcovid', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tintuc.ngaythang')),
            ],
            options={
                'db_table': 'travinhcovid',
            },
        ),
        migrations.CreateModel(
            name='Tiengiangvacine',
            fields=[
                ('idvaccine', models.AutoField(primary_key=True, serialize=False)),
                ('khphanbo', models.IntegerField(blank=True, null=True)),
                ('phanbothucte', models.IntegerField(blank=True, null=True)),
                ('danso', models.IntegerField(blank=True, null=True)),
                ('solieudatiem', models.IntegerField(blank=True, null=True)),
                ('ngaycapnhat', models.ForeignKey(blank=True, db_column='ngaycapnhat', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tintuc.ngaythang')),
            ],
            options={
                'db_table': 'tiengiangvacine',
            },
        ),
        migrations.CreateModel(
            name='Tiengiangcovid',
            fields=[
                ('idcovid', models.AutoField(primary_key=True, serialize=False)),
                ('tongsoca', models.IntegerField(blank=True, null=True)),
                ('homnay', models.IntegerField(blank=True, null=True)),
                ('tuvong', models.IntegerField(blank=True, null=True)),
                ('ngaycapnhatcovid', models.ForeignKey(blank=True, db_column='ngaycapnhatcovid', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tintuc.ngaythang')),
            ],
            options={
                'db_table': 'tiengiangcovid',
            },
        ),
        migrations.CreateModel(
            name='Thuathienhuevacine',
            fields=[
                ('idvaccine', models.AutoField(primary_key=True, serialize=False)),
                ('khphanbo', models.IntegerField(blank=True, null=True)),
                ('phanbothucte', models.IntegerField(blank=True, null=True)),
                ('danso', models.IntegerField(blank=True, null=True)),
                ('solieudatiem', models.IntegerField(blank=True, null=True)),
                ('ngaycapnhat', models.ForeignKey(blank=True, db_column='ngaycapnhat', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tintuc.ngaythang')),
            ],
            options={
                'db_table': 'thuathienhuevacine',
            },
        ),
        migrations.CreateModel(
            name='Thuathienhuecovid',
            fields=[
                ('idcovid', models.AutoField(primary_key=True, serialize=False)),
                ('tongsoca', models.IntegerField(blank=True, null=True)),
                ('homnay', models.IntegerField(blank=True, null=True)),
                ('tuvong', models.IntegerField(blank=True, null=True)),
                ('ngaycapnhatcovid', models.ForeignKey(blank=True, db_column='ngaycapnhatcovid', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tintuc.ngaythang')),
            ],
            options={
                'db_table': 'thuathienhuecovid',
            },
        ),
        migrations.CreateModel(
            name='Thanhhoavacine',
            fields=[
                ('idvaccine', models.AutoField(primary_key=True, serialize=False)),
                ('khphanbo', models.IntegerField(blank=True, null=True)),
                ('phanbothucte', models.IntegerField(blank=True, null=True)),
                ('danso', models.IntegerField(blank=True, null=True)),
                ('solieudatiem', models.IntegerField(blank=True, null=True)),
                ('ngaycapnhat', models.ForeignKey(blank=True, db_column='ngaycapnhat', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tintuc.ngaythang')),
            ],
            options={
                'db_table': 'thanhhoavacine',
            },
        ),
        migrations.CreateModel(
            name='Thanhhoacovid',
            fields=[
                ('idcovid', models.AutoField(primary_key=True, serialize=False)),
                ('tongsoca', models.IntegerField(blank=True, null=True)),
                ('homnay', models.IntegerField(blank=True, null=True)),
                ('tuvong', models.IntegerField(blank=True, null=True)),
                ('ngaycapnhatcovid', models.ForeignKey(blank=True, db_column='ngaycapnhatcovid', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tintuc.ngaythang')),
            ],
            options={
                'db_table': 'thanhhoacovid',
            },
        ),
        migrations.CreateModel(
            name='Thainguyenvacine',
            fields=[
                ('idvaccine', models.AutoField(primary_key=True, serialize=False)),
                ('khphanbo', models.IntegerField(blank=True, null=True)),
                ('phanbothucte', models.IntegerField(blank=True, null=True)),
                ('danso', models.IntegerField(blank=True, null=True)),
                ('solieudatiem', models.IntegerField(blank=True, null=True)),
                ('ngaycapnhat', models.ForeignKey(blank=True, db_column='ngaycapnhat', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tintuc.ngaythang')),
            ],
            options={
                'db_table': 'thainguyenvacine',
            },
        ),
        migrations.CreateModel(
            name='Thainguyencovid',
            fields=[
                ('idcovid', models.AutoField(primary_key=True, serialize=False)),
                ('tongsoca', models.IntegerField(blank=True, null=True)),
                ('homnay', models.IntegerField(blank=True, null=True)),
                ('tuvong', models.IntegerField(blank=True, null=True)),
                ('ngaycapnhatcovid', models.ForeignKey(blank=True, db_column='ngaycapnhatcovid', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tintuc.ngaythang')),
            ],
            options={
                'db_table': 'thainguyencovid',
            },
        ),
        migrations.CreateModel(
            name='Thaibinhvacine',
            fields=[
                ('idvaccine', models.AutoField(primary_key=True, serialize=False)),
                ('khphanbo', models.IntegerField(blank=True, null=True)),
                ('phanbothucte', models.IntegerField(blank=True, null=True)),
                ('danso', models.IntegerField(blank=True, null=True)),
                ('solieudatiem', models.IntegerField(blank=True, null=True)),
                ('ngaycapnhat', models.ForeignKey(blank=True, db_column='ngaycapnhat', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tintuc.ngaythang')),
            ],
            options={
                'db_table': 'thaibinhvacine',
            },
        ),
        migrations.CreateModel(
            name='Thaibinhcovid',
            fields=[
                ('idcovid', models.AutoField(primary_key=True, serialize=False)),
                ('tongsoca', models.IntegerField(blank=True, null=True)),
                ('homnay', models.IntegerField(blank=True, null=True)),
                ('tuvong', models.IntegerField(blank=True, null=True)),
                ('ngaycapnhatcovid', models.ForeignKey(blank=True, db_column='ngaycapnhatcovid', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tintuc.ngaythang')),
            ],
            options={
                'db_table': 'thaibinhcovid',
            },
        ),
        migrations.CreateModel(
            name='Tayninhvacine',
            fields=[
                ('idvaccine', models.AutoField(primary_key=True, serialize=False)),
                ('khphanbo', models.IntegerField(blank=True, null=True)),
                ('phanbothucte', models.IntegerField(blank=True, null=True)),
                ('danso', models.IntegerField(blank=True, null=True)),
                ('solieudatiem', models.IntegerField(blank=True, null=True)),
                ('ngaycapnhat', models.ForeignKey(blank=True, db_column='ngaycapnhat', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tintuc.ngaythang')),
            ],
            options={
                'db_table': 'tayninhvacine',
            },
        ),
        migrations.CreateModel(
            name='Tayninhcovid',
            fields=[
                ('idcovid', models.AutoField(primary_key=True, serialize=False)),
                ('tongsoca', models.IntegerField(blank=True, null=True)),
                ('homnay', models.IntegerField(blank=True, null=True)),
                ('tuvong', models.IntegerField(blank=True, null=True)),
                ('ngaycapnhatcovid', models.ForeignKey(blank=True, db_column='ngaycapnhatcovid', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tintuc.ngaythang')),
            ],
            options={
                'db_table': 'tayninhcovid',
            },
        ),
        migrations.CreateModel(
            name='Sonlavacine',
            fields=[
                ('idvaccine', models.AutoField(primary_key=True, serialize=False)),
                ('khphanbo', models.IntegerField(blank=True, null=True)),
                ('phanbothucte', models.IntegerField(blank=True, null=True)),
                ('danso', models.IntegerField(blank=True, null=True)),
                ('solieudatiem', models.IntegerField(blank=True, null=True)),
                ('ngaycapnhat', models.ForeignKey(blank=True, db_column='ngaycapnhat', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tintuc.ngaythang')),
            ],
            options={
                'db_table': 'sonlavacine',
            },
        ),
        migrations.CreateModel(
            name='Sonlacovid',
            fields=[
                ('idcovid', models.AutoField(primary_key=True, serialize=False)),
                ('tongsoca', models.IntegerField(blank=True, null=True)),
                ('homnay', models.IntegerField(blank=True, null=True)),
                ('tuvong', models.IntegerField(blank=True, null=True)),
                ('ngaycapnhatcovid', models.ForeignKey(blank=True, db_column='ngaycapnhatcovid', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tintuc.ngaythang')),
            ],
            options={
                'db_table': 'sonlacovid',
            },
        ),
        migrations.CreateModel(
            name='Soctrangvacine',
            fields=[
                ('idvaccine', models.AutoField(primary_key=True, serialize=False)),
                ('khphanbo', models.IntegerField(blank=True, null=True)),
                ('phanbothucte', models.IntegerField(blank=True, null=True)),
                ('danso', models.IntegerField(blank=True, null=True)),
                ('solieudatiem', models.IntegerField(blank=True, null=True)),
                ('ngaycapnhat', models.ForeignKey(blank=True, db_column='ngaycapnhat', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tintuc.ngaythang')),
            ],
            options={
                'db_table': 'soctrangvacine',
            },
        ),
        migrations.CreateModel(
            name='Soctrangcovid',
            fields=[
                ('idcovid', models.AutoField(primary_key=True, serialize=False)),
                ('tongsoca', models.IntegerField(blank=True, null=True)),
                ('homnay', models.IntegerField(blank=True, null=True)),
                ('tuvong', models.IntegerField(blank=True, null=True)),
                ('ngaycapnhatcovid', models.ForeignKey(blank=True, db_column='ngaycapnhatcovid', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tintuc.ngaythang')),
            ],
            options={
                'db_table': 'soctrangcovid',
            },
        ),
        migrations.CreateModel(
            name='Quangtrivacine',
            fields=[
                ('idvaccine', models.AutoField(primary_key=True, serialize=False)),
                ('khphanbo', models.IntegerField(blank=True, null=True)),
                ('phanbothucte', models.IntegerField(blank=True, null=True)),
                ('danso', models.IntegerField(blank=True, null=True)),
                ('solieudatiem', models.IntegerField(blank=True, null=True)),
                ('ngaycapnhat', models.ForeignKey(blank=True, db_column='ngaycapnhat', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tintuc.ngaythang')),
            ],
            options={
                'db_table': 'quangtrivacine',
            },
        ),
        migrations.CreateModel(
            name='Quangtricovid',
            fields=[
                ('idcovid', models.AutoField(primary_key=True, serialize=False)),
                ('tongsoca', models.IntegerField(blank=True, null=True)),
                ('homnay', models.IntegerField(blank=True, null=True)),
                ('tuvong', models.IntegerField(blank=True, null=True)),
                ('ngaycapnhatcovid', models.ForeignKey(blank=True, db_column='ngaycapnhatcovid', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tintuc.ngaythang')),
            ],
            options={
                'db_table': 'quangtricovid',
            },
        ),
        migrations.CreateModel(
            name='Quangninhvacine',
            fields=[
                ('idvaccine', models.AutoField(primary_key=True, serialize=False)),
                ('khphanbo', models.IntegerField(blank=True, null=True)),
                ('phanbothucte', models.IntegerField(blank=True, null=True)),
                ('danso', models.IntegerField(blank=True, null=True)),
                ('solieudatiem', models.IntegerField(blank=True, null=True)),
                ('ngaycapnhat', models.ForeignKey(blank=True, db_column='ngaycapnhat', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tintuc.ngaythang')),
            ],
            options={
                'db_table': 'quangninhvacine',
            },
        ),
        migrations.CreateModel(
            name='Quangninhcovid',
            fields=[
                ('idcovid', models.AutoField(primary_key=True, serialize=False)),
                ('tongsoca', models.IntegerField(blank=True, null=True)),
                ('homnay', models.IntegerField(blank=True, null=True)),
                ('tuvong', models.IntegerField(blank=True, null=True)),
                ('ngaycapnhatcovid', models.ForeignKey(blank=True, db_column='ngaycapnhatcovid', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tintuc.ngaythang')),
            ],
            options={
                'db_table': 'quangninhcovid',
            },
        ),
        migrations.CreateModel(
            name='Quangngaivacine',
            fields=[
                ('idvaccine', models.AutoField(primary_key=True, serialize=False)),
                ('khphanbo', models.IntegerField(blank=True, null=True)),
                ('phanbothucte', models.IntegerField(blank=True, null=True)),
                ('danso', models.IntegerField(blank=True, null=True)),
                ('solieudatiem', models.IntegerField(blank=True, null=True)),
                ('ngaycapnhat', models.ForeignKey(blank=True, db_column='ngaycapnhat', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tintuc.ngaythang')),
            ],
            options={
                'db_table': 'quangngaivacine',
            },
        ),
        migrations.CreateModel(
            name='Quangngaicovid',
            fields=[
                ('idcovid', models.AutoField(primary_key=True, serialize=False)),
                ('tongsoca', models.IntegerField(blank=True, null=True)),
                ('homnay', models.IntegerField(blank=True, null=True)),
                ('tuvong', models.IntegerField(blank=True, null=True)),
                ('ngaycapnhatcovid', models.ForeignKey(blank=True, db_column='ngaycapnhatcovid', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tintuc.ngaythang')),
            ],
            options={
                'db_table': 'quangngaicovid',
            },
        ),
        migrations.CreateModel(
            name='Quangnamvacine',
            fields=[
                ('idvaccine', models.AutoField(primary_key=True, serialize=False)),
                ('khphanbo', models.IntegerField(blank=True, null=True)),
                ('phanbothucte', models.IntegerField(blank=True, null=True)),
                ('danso', models.IntegerField(blank=True, null=True)),
                ('solieudatiem', models.IntegerField(blank=True, null=True)),
                ('ngaycapnhat', models.ForeignKey(blank=True, db_column='ngaycapnhat', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tintuc.ngaythang')),
            ],
            options={
                'db_table': 'quangnamvacine',
            },
        ),
        migrations.CreateModel(
            name='Quangnamcovid',
            fields=[
                ('idcovid', models.AutoField(primary_key=True, serialize=False)),
                ('tongsoca', models.IntegerField(blank=True, null=True)),
                ('homnay', models.IntegerField(blank=True, null=True)),
                ('tuvong', models.IntegerField(blank=True, null=True)),
                ('ngaycapnhatcovid', models.ForeignKey(blank=True, db_column='ngaycapnhatcovid', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tintuc.ngaythang')),
            ],
            options={
                'db_table': 'quangnamcovid',
            },
        ),
        migrations.CreateModel(
            name='Quangbinhvacine',
            fields=[
                ('idvaccine', models.AutoField(primary_key=True, serialize=False)),
                ('khphanbo', models.IntegerField(blank=True, null=True)),
                ('phanbothucte', models.IntegerField(blank=True, null=True)),
                ('danso', models.IntegerField(blank=True, null=True)),
                ('solieudatiem', models.IntegerField(blank=True, null=True)),
                ('ngaycapnhat', models.ForeignKey(blank=True, db_column='ngaycapnhat', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tintuc.ngaythang')),
            ],
            options={
                'db_table': 'quangbinhvacine',
            },
        ),
        migrations.CreateModel(
            name='Quangbinhcovid',
            fields=[
                ('idcovid', models.AutoField(primary_key=True, serialize=False)),
                ('tongsoca', models.IntegerField(blank=True, null=True)),
                ('homnay', models.IntegerField(blank=True, null=True)),
                ('tuvong', models.IntegerField(blank=True, null=True)),
                ('ngaycapnhatcovid', models.ForeignKey(blank=True, db_column='ngaycapnhatcovid', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tintuc.ngaythang')),
            ],
            options={
                'db_table': 'quangbinhcovid',
            },
        ),
        migrations.CreateModel(
            name='Phuyenvacine',
            fields=[
                ('idvaccine', models.AutoField(primary_key=True, serialize=False)),
                ('khphanbo', models.IntegerField(blank=True, null=True)),
                ('phanbothucte', models.IntegerField(blank=True, null=True)),
                ('danso', models.IntegerField(blank=True, null=True)),
                ('solieudatiem', models.IntegerField(blank=True, null=True)),
                ('ngaycapnhat', models.ForeignKey(blank=True, db_column='ngaycapnhat', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tintuc.ngaythang')),
            ],
            options={
                'db_table': 'phuyenvacine',
            },
        ),
        migrations.CreateModel(
            name='Phuyencovid',
            fields=[
                ('idcovid', models.AutoField(primary_key=True, serialize=False)),
                ('tongsoca', models.IntegerField(blank=True, null=True)),
                ('homnay', models.IntegerField(blank=True, null=True)),
                ('tuvong', models.IntegerField(blank=True, null=True)),
                ('ngaycapnhatcovid', models.ForeignKey(blank=True, db_column='ngaycapnhatcovid', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tintuc.ngaythang')),
            ],
            options={
                'db_table': 'phuyencovid',
            },
        ),
        migrations.CreateModel(
            name='Phuthovacine',
            fields=[
                ('idvaccine', models.AutoField(primary_key=True, serialize=False)),
                ('khphanbo', models.IntegerField(blank=True, null=True)),
                ('phanbothucte', models.IntegerField(blank=True, null=True)),
                ('danso', models.IntegerField(blank=True, null=True)),
                ('solieudatiem', models.IntegerField(blank=True, null=True)),
                ('ngaycapnhat', models.ForeignKey(blank=True, db_column='ngaycapnhat', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tintuc.ngaythang')),
            ],
            options={
                'db_table': 'phuthovacine',
            },
        ),
        migrations.CreateModel(
            name='Phuthocovid',
            fields=[
                ('idcovid', models.AutoField(primary_key=True, serialize=False)),
                ('tongsoca', models.IntegerField(blank=True, null=True)),
                ('homnay', models.IntegerField(blank=True, null=True)),
                ('tuvong', models.IntegerField(blank=True, null=True)),
                ('ngaycapnhatcovid', models.ForeignKey(blank=True, db_column='ngaycapnhatcovid', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tintuc.ngaythang')),
            ],
            options={
                'db_table': 'phuthocovid',
            },
        ),
        migrations.CreateModel(
            name='Ninhthuanvacine',
            fields=[
                ('idvaccine', models.AutoField(primary_key=True, serialize=False)),
                ('khphanbo', models.IntegerField(blank=True, null=True)),
                ('phanbothucte', models.IntegerField(blank=True, null=True)),
                ('danso', models.IntegerField(blank=True, null=True)),
                ('solieudatiem', models.IntegerField(blank=True, null=True)),
                ('ngaycapnhat', models.ForeignKey(blank=True, db_column='ngaycapnhat', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tintuc.ngaythang')),
            ],
            options={
                'db_table': 'ninhthuanvacine',
            },
        ),
        migrations.CreateModel(
            name='Ninhthuancovid',
            fields=[
                ('idcovid', models.AutoField(primary_key=True, serialize=False)),
                ('tongsoca', models.IntegerField(blank=True, null=True)),
                ('homnay', models.IntegerField(blank=True, null=True)),
                ('tuvong', models.IntegerField(blank=True, null=True)),
                ('ngaycapnhatcovid', models.ForeignKey(blank=True, db_column='ngaycapnhatcovid', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tintuc.ngaythang')),
            ],
            options={
                'db_table': 'ninhthuancovid',
            },
        ),
        migrations.CreateModel(
            name='Ninhbinhvacine',
            fields=[
                ('idvaccine', models.AutoField(primary_key=True, serialize=False)),
                ('khphanbo', models.IntegerField(blank=True, null=True)),
                ('phanbothucte', models.IntegerField(blank=True, null=True)),
                ('danso', models.IntegerField(blank=True, null=True)),
                ('solieudatiem', models.IntegerField(blank=True, null=True)),
                ('ngaycapnhat', models.ForeignKey(blank=True, db_column='ngaycapnhat', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tintuc.ngaythang')),
            ],
            options={
                'db_table': 'ninhbinhvacine',
            },
        ),
        migrations.CreateModel(
            name='Ninhbinhcovid',
            fields=[
                ('idcovid', models.AutoField(primary_key=True, serialize=False)),
                ('tongsoca', models.IntegerField(blank=True, null=True)),
                ('homnay', models.IntegerField(blank=True, null=True)),
                ('tuvong', models.IntegerField(blank=True, null=True)),
                ('ngaycapnhatcovid', models.ForeignKey(blank=True, db_column='ngaycapnhatcovid', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tintuc.ngaythang')),
            ],
            options={
                'db_table': 'ninhbinhcovid',
            },
        ),
        migrations.CreateModel(
            name='Ngheanvacine',
            fields=[
                ('idvaccine', models.AutoField(primary_key=True, serialize=False)),
                ('khphanbo', models.IntegerField(blank=True, null=True)),
                ('phanbothucte', models.IntegerField(blank=True, null=True)),
                ('danso', models.IntegerField(blank=True, null=True)),
                ('solieudatiem', models.IntegerField(blank=True, null=True)),
                ('ngaycapnhat', models.ForeignKey(blank=True, db_column='ngaycapnhat', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tintuc.ngaythang')),
            ],
            options={
                'db_table': 'ngheanvacine',
            },
        ),
        migrations.CreateModel(
            name='Ngheancovid',
            fields=[
                ('idcovid', models.AutoField(primary_key=True, serialize=False)),
                ('tongsoca', models.IntegerField(blank=True, null=True)),
                ('homnay', models.IntegerField(blank=True, null=True)),
                ('tuvong', models.IntegerField(blank=True, null=True)),
                ('ngaycapnhatcovid', models.ForeignKey(blank=True, db_column='ngaycapnhatcovid', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tintuc.ngaythang')),
            ],
            options={
                'db_table': 'ngheancovid',
            },
        ),
        migrations.CreateModel(
            name='Namdinhvacine',
            fields=[
                ('idvaccine', models.AutoField(primary_key=True, serialize=False)),
                ('khphanbo', models.IntegerField(blank=True, null=True)),
                ('phanbothucte', models.IntegerField(blank=True, null=True)),
                ('danso', models.IntegerField(blank=True, null=True)),
                ('solieudatiem', models.IntegerField(blank=True, null=True)),
                ('ngaycapnhat', models.ForeignKey(blank=True, db_column='ngaycapnhat', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tintuc.ngaythang')),
            ],
            options={
                'db_table': 'namdinhvacine',
            },
        ),
        migrations.CreateModel(
            name='Namdinhcovid',
            fields=[
                ('idcovid', models.AutoField(primary_key=True, serialize=False)),
                ('tongsoca', models.IntegerField(blank=True, null=True)),
                ('homnay', models.IntegerField(blank=True, null=True)),
                ('tuvong', models.IntegerField(blank=True, null=True)),
                ('ngaycapnhatcovid', models.ForeignKey(blank=True, db_column='ngaycapnhatcovid', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tintuc.ngaythang')),
            ],
            options={
                'db_table': 'namdinhcovid',
            },
        ),
        migrations.CreateModel(
            name='Longanvacine',
            fields=[
                ('idvaccine', models.AutoField(primary_key=True, serialize=False)),
                ('khphanbo', models.IntegerField(blank=True, null=True)),
                ('phanbothucte', models.IntegerField(blank=True, null=True)),
                ('danso', models.IntegerField(blank=True, null=True)),
                ('solieudatiem', models.IntegerField(blank=True, null=True)),
                ('ngaycapnhat', models.ForeignKey(blank=True, db_column='ngaycapnhat', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tintuc.ngaythang')),
            ],
            options={
                'db_table': 'longanvacine',
            },
        ),
        migrations.CreateModel(
            name='Longancovid',
            fields=[
                ('idcovid', models.AutoField(primary_key=True, serialize=False)),
                ('tongsoca', models.IntegerField(blank=True, null=True)),
                ('homnay', models.IntegerField(blank=True, null=True)),
                ('tuvong', models.IntegerField(blank=True, null=True)),
                ('ngaycapnhatcovid', models.ForeignKey(blank=True, db_column='ngaycapnhatcovid', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tintuc.ngaythang')),
            ],
            options={
                'db_table': 'longancovid',
            },
        ),
        migrations.CreateModel(
            name='Laocaivacine',
            fields=[
                ('idvaccine', models.AutoField(primary_key=True, serialize=False)),
                ('khphanbo', models.IntegerField(blank=True, null=True)),
                ('phanbothucte', models.IntegerField(blank=True, null=True)),
                ('danso', models.IntegerField(blank=True, null=True)),
                ('solieudatiem', models.IntegerField(blank=True, null=True)),
                ('ngaycapnhat', models.ForeignKey(blank=True, db_column='ngaycapnhat', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tintuc.ngaythang')),
            ],
            options={
                'db_table': 'laocaivacine',
            },
        ),
        migrations.CreateModel(
            name='Laocaicovid',
            fields=[
                ('idcovid', models.AutoField(primary_key=True, serialize=False)),
                ('tongsoca', models.IntegerField(blank=True, null=True)),
                ('homnay', models.IntegerField(blank=True, null=True)),
                ('tuvong', models.IntegerField(blank=True, null=True)),
                ('ngaycapnhatcovid', models.ForeignKey(blank=True, db_column='ngaycapnhatcovid', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tintuc.ngaythang')),
            ],
            options={
                'db_table': 'laocaicovid',
            },
        ),
        migrations.CreateModel(
            name='Langsonvacine',
            fields=[
                ('idvaccine', models.AutoField(primary_key=True, serialize=False)),
                ('khphanbo', models.IntegerField(blank=True, null=True)),
                ('phanbothucte', models.IntegerField(blank=True, null=True)),
                ('danso', models.IntegerField(blank=True, null=True)),
                ('solieudatiem', models.IntegerField(blank=True, null=True)),
                ('ngaycapnhat', models.ForeignKey(blank=True, db_column='ngaycapnhat', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tintuc.ngaythang')),
            ],
            options={
                'db_table': 'langsonvacine',
            },
        ),
        migrations.CreateModel(
            name='Langsoncovid',
            fields=[
                ('idcovid', models.AutoField(primary_key=True, serialize=False)),
                ('tongsoca', models.IntegerField(blank=True, null=True)),
                ('homnay', models.IntegerField(blank=True, null=True)),
                ('tuvong', models.IntegerField(blank=True, null=True)),
                ('ngaycapnhatcovid', models.ForeignKey(blank=True, db_column='ngaycapnhatcovid', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tintuc.ngaythang')),
            ],
            options={
                'db_table': 'langsoncovid',
            },
        ),
        migrations.CreateModel(
            name='Lamdongvacine',
            fields=[
                ('idvaccine', models.AutoField(primary_key=True, serialize=False)),
                ('khphanbo', models.IntegerField(blank=True, null=True)),
                ('phanbothucte', models.IntegerField(blank=True, null=True)),
                ('danso', models.IntegerField(blank=True, null=True)),
                ('solieudatiem', models.IntegerField(blank=True, null=True)),
                ('ngaycapnhat', models.ForeignKey(blank=True, db_column='ngaycapnhat', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tintuc.ngaythang')),
            ],
            options={
                'db_table': 'lamdongvacine',
            },
        ),
        migrations.CreateModel(
            name='Lamdongcovid',
            fields=[
                ('idcovid', models.AutoField(primary_key=True, serialize=False)),
                ('tongsoca', models.IntegerField(blank=True, null=True)),
                ('homnay', models.IntegerField(blank=True, null=True)),
                ('tuvong', models.IntegerField(blank=True, null=True)),
                ('ngaycapnhatcovid', models.ForeignKey(blank=True, db_column='ngaycapnhatcovid', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tintuc.ngaythang')),
            ],
            options={
                'db_table': 'lamdongcovid',
            },
        ),
        migrations.CreateModel(
            name='Laichauvacine',
            fields=[
                ('idvaccine', models.AutoField(primary_key=True, serialize=False)),
                ('khphanbo', models.IntegerField(blank=True, null=True)),
                ('phanbothucte', models.IntegerField(blank=True, null=True)),
                ('danso', models.IntegerField(blank=True, null=True)),
                ('solieudatiem', models.IntegerField(blank=True, null=True)),
                ('ngaycapnhat', models.ForeignKey(blank=True, db_column='ngaycapnhat', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tintuc.ngaythang')),
            ],
            options={
                'db_table': 'laichauvacine',
            },
        ),
        migrations.CreateModel(
            name='Laichaucovid',
            fields=[
                ('idcovid', models.AutoField(primary_key=True, serialize=False)),
                ('tongsoca', models.IntegerField(blank=True, null=True)),
                ('homnay', models.IntegerField(blank=True, null=True)),
                ('tuvong', models.IntegerField(blank=True, null=True)),
                ('ngaycapnhatcovid', models.ForeignKey(blank=True, db_column='ngaycapnhatcovid', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tintuc.ngaythang')),
            ],
            options={
                'db_table': 'laichaucovid',
            },
        ),
        migrations.CreateModel(
            name='Kontumvacine',
            fields=[
                ('idvaccine', models.AutoField(primary_key=True, serialize=False)),
                ('khphanbo', models.IntegerField(blank=True, null=True)),
                ('phanbothucte', models.IntegerField(blank=True, null=True)),
                ('danso', models.IntegerField(blank=True, null=True)),
                ('solieudatiem', models.IntegerField(blank=True, null=True)),
                ('ngaycapnhat', models.ForeignKey(blank=True, db_column='ngaycapnhat', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tintuc.ngaythang')),
            ],
            options={
                'db_table': 'kontumvacine',
            },
        ),
        migrations.CreateModel(
            name='Kontumcovid',
            fields=[
                ('idcovid', models.AutoField(primary_key=True, serialize=False)),
                ('tongsoca', models.IntegerField(blank=True, null=True)),
                ('homnay', models.IntegerField(blank=True, null=True)),
                ('tuvong', models.IntegerField(blank=True, null=True)),
                ('ngaycapnhatcovid', models.ForeignKey(blank=True, db_column='ngaycapnhatcovid', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tintuc.ngaythang')),
            ],
            options={
                'db_table': 'kontumcovid',
            },
        ),
        migrations.CreateModel(
            name='Kiengiangvacine',
            fields=[
                ('idvaccine', models.AutoField(primary_key=True, serialize=False)),
                ('khphanbo', models.IntegerField(blank=True, null=True)),
                ('phanbothucte', models.IntegerField(blank=True, null=True)),
                ('danso', models.IntegerField(blank=True, null=True)),
                ('solieudatiem', models.IntegerField(blank=True, null=True)),
                ('ngaycapnhat', models.ForeignKey(blank=True, db_column='ngaycapnhat', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tintuc.ngaythang')),
            ],
            options={
                'db_table': 'kiengiangvacine',
            },
        ),
        migrations.CreateModel(
            name='Kiengiangcovid',
            fields=[
                ('idcovid', models.AutoField(primary_key=True, serialize=False)),
                ('tongsoca', models.IntegerField(blank=True, null=True)),
                ('homnay', models.IntegerField(blank=True, null=True)),
                ('tuvong', models.IntegerField(blank=True, null=True)),
                ('ngaycapnhatcovid', models.ForeignKey(blank=True, db_column='ngaycapnhatcovid', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tintuc.ngaythang')),
            ],
            options={
                'db_table': 'kiengiangcovid',
            },
        ),
        migrations.CreateModel(
            name='Khanhhoavacine',
            fields=[
                ('idvaccine', models.AutoField(primary_key=True, serialize=False)),
                ('khphanbo', models.IntegerField(blank=True, null=True)),
                ('phanbothucte', models.IntegerField(blank=True, null=True)),
                ('danso', models.IntegerField(blank=True, null=True)),
                ('solieudatiem', models.IntegerField(blank=True, null=True)),
                ('ngaycapnhat', models.ForeignKey(blank=True, db_column='ngaycapnhat', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tintuc.ngaythang')),
            ],
            options={
                'db_table': 'khanhhoavacine',
            },
        ),
        migrations.CreateModel(
            name='Khanhhoacovid',
            fields=[
                ('idcovid', models.AutoField(primary_key=True, serialize=False)),
                ('tongsoca', models.IntegerField(blank=True, null=True)),
                ('homnay', models.IntegerField(blank=True, null=True)),
                ('tuvong', models.IntegerField(blank=True, null=True)),
                ('ngaycapnhatcovid', models.ForeignKey(blank=True, db_column='ngaycapnhatcovid', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tintuc.ngaythang')),
            ],
            options={
                'db_table': 'khanhhoacovid',
            },
        ),
        migrations.CreateModel(
            name='Hungyenvacine',
            fields=[
                ('idvaccine', models.AutoField(primary_key=True, serialize=False)),
                ('khphanbo', models.IntegerField(blank=True, null=True)),
                ('phanbothucte', models.IntegerField(blank=True, null=True)),
                ('danso', models.IntegerField(blank=True, null=True)),
                ('solieudatiem', models.IntegerField(blank=True, null=True)),
                ('ngaycapnhat', models.ForeignKey(blank=True, db_column='ngaycapnhat', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tintuc.ngaythang')),
            ],
            options={
                'db_table': 'hungyenvacine',
            },
        ),
        migrations.CreateModel(
            name='Hungyencovid',
            fields=[
                ('idcovid', models.AutoField(primary_key=True, serialize=False)),
                ('tongsoca', models.IntegerField(blank=True, null=True)),
                ('homnay', models.IntegerField(blank=True, null=True)),
                ('tuvong', models.IntegerField(blank=True, null=True)),
                ('ngaycapnhatcovid', models.ForeignKey(blank=True, db_column='ngaycapnhatcovid', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tintuc.ngaythang')),
            ],
            options={
                'db_table': 'hungyencovid',
            },
        ),
        migrations.CreateModel(
            name='Hochiminhvacine',
            fields=[
                ('idvaccine', models.AutoField(primary_key=True, serialize=False)),
                ('khphanbo', models.IntegerField(blank=True, null=True)),
                ('phanbothucte', models.IntegerField(blank=True, null=True)),
                ('danso', models.IntegerField(blank=True, null=True)),
                ('solieudatiem', models.IntegerField(blank=True, null=True)),
                ('ngaycapnhat', models.ForeignKey(blank=True, db_column='ngaycapnhat', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tintuc.ngaythang')),
            ],
            options={
                'db_table': 'hochiminhvacine',
            },
        ),
        migrations.CreateModel(
            name='Hochiminhcovid',
            fields=[
                ('idcovid', models.AutoField(primary_key=True, serialize=False)),
                ('tongsoca', models.IntegerField(blank=True, null=True)),
                ('homnay', models.IntegerField(blank=True, null=True)),
                ('tuvong', models.IntegerField(blank=True, null=True)),
                ('ngaycapnhatcovid', models.ForeignKey(blank=True, db_column='ngaycapnhatcovid', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tintuc.ngaythang')),
            ],
            options={
                'db_table': 'hochiminhcovid',
            },
        ),
        migrations.CreateModel(
            name='Hoabinhvacine',
            fields=[
                ('idvaccine', models.AutoField(primary_key=True, serialize=False)),
                ('khphanbo', models.IntegerField(blank=True, null=True)),
                ('phanbothucte', models.IntegerField(blank=True, null=True)),
                ('danso', models.IntegerField(blank=True, null=True)),
                ('solieudatiem', models.IntegerField(blank=True, null=True)),
                ('ngaycapnhat', models.ForeignKey(blank=True, db_column='ngaycapnhat', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tintuc.ngaythang')),
            ],
            options={
                'db_table': 'hoabinhvacine',
            },
        ),
        migrations.CreateModel(
            name='Hoabinhcovid',
            fields=[
                ('idcovid', models.AutoField(primary_key=True, serialize=False)),
                ('tongsoca', models.IntegerField(blank=True, null=True)),
                ('homnay', models.IntegerField(blank=True, null=True)),
                ('tuvong', models.IntegerField(blank=True, null=True)),
                ('ngaycapnhatcovid', models.ForeignKey(blank=True, db_column='ngaycapnhatcovid', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tintuc.ngaythang')),
            ],
            options={
                'db_table': 'hoabinhcovid',
            },
        ),
        migrations.CreateModel(
            name='Haugiangvacine',
            fields=[
                ('idvaccine', models.AutoField(primary_key=True, serialize=False)),
                ('khphanbo', models.IntegerField(blank=True, null=True)),
                ('phanbothucte', models.IntegerField(blank=True, null=True)),
                ('danso', models.IntegerField(blank=True, null=True)),
                ('solieudatiem', models.IntegerField(blank=True, null=True)),
                ('ngaycapnhat', models.ForeignKey(blank=True, db_column='ngaycapnhat', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tintuc.ngaythang')),
            ],
            options={
                'db_table': 'haugiangvacine',
            },
        ),
        migrations.CreateModel(
            name='Haugiangcovid',
            fields=[
                ('idcovid', models.AutoField(primary_key=True, serialize=False)),
                ('tongsoca', models.IntegerField(blank=True, null=True)),
                ('homnay', models.IntegerField(blank=True, null=True)),
                ('tuvong', models.IntegerField(blank=True, null=True)),
                ('ngaycapnhatcovid', models.ForeignKey(blank=True, db_column='ngaycapnhatcovid', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tintuc.ngaythang')),
            ],
            options={
                'db_table': 'haugiangcovid',
            },
        ),
        migrations.CreateModel(
            name='Hatinhvacine',
            fields=[
                ('idvaccine', models.AutoField(primary_key=True, serialize=False)),
                ('khphanbo', models.IntegerField(blank=True, null=True)),
                ('phanbothucte', models.IntegerField(blank=True, null=True)),
                ('danso', models.IntegerField(blank=True, null=True)),
                ('solieudatiem', models.IntegerField(blank=True, null=True)),
                ('ngaycapnhat', models.ForeignKey(blank=True, db_column='ngaycapnhat', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tintuc.ngaythang')),
            ],
            options={
                'db_table': 'hatinhvacine',
            },
        ),
        migrations.CreateModel(
            name='Hatinhcovid',
            fields=[
                ('idcovid', models.AutoField(primary_key=True, serialize=False)),
                ('tongsoca', models.IntegerField(blank=True, null=True)),
                ('homnay', models.IntegerField(blank=True, null=True)),
                ('tuvong', models.IntegerField(blank=True, null=True)),
                ('ngaycapnhatcovid', models.ForeignKey(blank=True, db_column='ngaycapnhatcovid', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tintuc.ngaythang')),
            ],
            options={
                'db_table': 'hatinhcovid',
            },
        ),
        migrations.CreateModel(
            name='Hanoivacine',
            fields=[
                ('idvaccine', models.AutoField(primary_key=True, serialize=False)),
                ('khphanbo', models.IntegerField(blank=True, null=True)),
                ('phanbothucte', models.IntegerField(blank=True, null=True)),
                ('danso', models.IntegerField(blank=True, null=True)),
                ('solieudatiem', models.IntegerField(blank=True, null=True)),
                ('ngaycapnhat', models.ForeignKey(blank=True, db_column='ngaycapnhat', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tintuc.ngaythang')),
            ],
            options={
                'db_table': 'hanoivacine',
            },
        ),
        migrations.CreateModel(
            name='Hanoicovid',
            fields=[
                ('idcovid', models.AutoField(primary_key=True, serialize=False)),
                ('tongsoca', models.IntegerField(blank=True, null=True)),
                ('homnay', models.IntegerField(blank=True, null=True)),
                ('tuvong', models.IntegerField(blank=True, null=True)),
                ('ngaycapnhatcovid', models.ForeignKey(blank=True, db_column='ngaycapnhatcovid', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tintuc.ngaythang')),
            ],
            options={
                'db_table': 'hanoicovid',
            },
        ),
        migrations.CreateModel(
            name='Hanamvacine',
            fields=[
                ('idvaccine', models.AutoField(primary_key=True, serialize=False)),
                ('khphanbo', models.IntegerField(blank=True, null=True)),
                ('phanbothucte', models.IntegerField(blank=True, null=True)),
                ('danso', models.IntegerField(blank=True, null=True)),
                ('solieudatiem', models.IntegerField(blank=True, null=True)),
                ('ngaycapnhat', models.ForeignKey(blank=True, db_column='ngaycapnhat', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tintuc.ngaythang')),
            ],
            options={
                'db_table': 'hanamvacine',
            },
        ),
        migrations.CreateModel(
            name='Hanamcovid',
            fields=[
                ('idcovid', models.AutoField(primary_key=True, serialize=False)),
                ('tongsoca', models.IntegerField(blank=True, null=True)),
                ('homnay', models.IntegerField(blank=True, null=True)),
                ('tuvong', models.IntegerField(blank=True, null=True)),
                ('ngaycapnhatcovid', models.ForeignKey(blank=True, db_column='ngaycapnhatcovid', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tintuc.ngaythang')),
            ],
            options={
                'db_table': 'hanamcovid',
            },
        ),
        migrations.CreateModel(
            name='Haiphongvacine',
            fields=[
                ('idvaccine', models.AutoField(primary_key=True, serialize=False)),
                ('khphanbo', models.IntegerField(blank=True, null=True)),
                ('phanbothucte', models.IntegerField(blank=True, null=True)),
                ('danso', models.IntegerField(blank=True, null=True)),
                ('solieudatiem', models.IntegerField(blank=True, null=True)),
                ('ngaycapnhat', models.ForeignKey(blank=True, db_column='ngaycapnhat', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tintuc.ngaythang')),
            ],
            options={
                'db_table': 'haiphongvacine',
            },
        ),
        migrations.CreateModel(
            name='Haiphongcovid',
            fields=[
                ('idcovid', models.AutoField(primary_key=True, serialize=False)),
                ('tongsoca', models.IntegerField(blank=True, null=True)),
                ('homnay', models.IntegerField(blank=True, null=True)),
                ('tuvong', models.IntegerField(blank=True, null=True)),
                ('ngaycapnhatcovid', models.ForeignKey(blank=True, db_column='ngaycapnhatcovid', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tintuc.ngaythang')),
            ],
            options={
                'db_table': 'haiphongcovid',
            },
        ),
        migrations.CreateModel(
            name='Haiduongvacine',
            fields=[
                ('idvaccine', models.AutoField(primary_key=True, serialize=False)),
                ('khphanbo', models.IntegerField(blank=True, null=True)),
                ('phanbothucte', models.IntegerField(blank=True, null=True)),
                ('danso', models.IntegerField(blank=True, null=True)),
                ('solieudatiem', models.IntegerField(blank=True, null=True)),
                ('ngaycapnhat', models.ForeignKey(blank=True, db_column='ngaycapnhat', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tintuc.ngaythang')),
            ],
            options={
                'db_table': 'haiduongvacine',
            },
        ),
        migrations.CreateModel(
            name='Haiduongcovid',
            fields=[
                ('idcovid', models.AutoField(primary_key=True, serialize=False)),
                ('tongsoca', models.IntegerField(blank=True, null=True)),
                ('homnay', models.IntegerField(blank=True, null=True)),
                ('tuvong', models.IntegerField(blank=True, null=True)),
                ('ngaycapnhatcovid', models.ForeignKey(blank=True, db_column='ngaycapnhatcovid', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tintuc.ngaythang')),
            ],
            options={
                'db_table': 'haiduongcovid',
            },
        ),
        migrations.CreateModel(
            name='Hagiangvacine',
            fields=[
                ('idvaccine', models.AutoField(primary_key=True, serialize=False)),
                ('khphanbo', models.IntegerField(blank=True, null=True)),
                ('phanbothucte', models.IntegerField(blank=True, null=True)),
                ('danso', models.IntegerField(blank=True, null=True)),
                ('solieudatiem', models.IntegerField(blank=True, null=True)),
                ('ngaycapnhat', models.ForeignKey(blank=True, db_column='ngaycapnhat', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tintuc.ngaythang')),
            ],
            options={
                'db_table': 'hagiangvacine',
            },
        ),
        migrations.CreateModel(
            name='Hagiangcovid',
            fields=[
                ('idcovid', models.AutoField(primary_key=True, serialize=False)),
                ('tongsoca', models.IntegerField(blank=True, null=True)),
                ('homnay', models.IntegerField(blank=True, null=True)),
                ('tuvong', models.IntegerField(blank=True, null=True)),
                ('ngaycapnhatcovid', models.ForeignKey(blank=True, db_column='ngaycapnhatcovid', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tintuc.ngaythang')),
            ],
            options={
                'db_table': 'hagiangcovid',
            },
        ),
        migrations.CreateModel(
            name='Gialaivacine',
            fields=[
                ('idvaccine', models.AutoField(primary_key=True, serialize=False)),
                ('khphanbo', models.IntegerField(blank=True, null=True)),
                ('phanbothucte', models.IntegerField(blank=True, null=True)),
                ('danso', models.IntegerField(blank=True, null=True)),
                ('solieudatiem', models.IntegerField(blank=True, null=True)),
                ('ngaycapnhat', models.ForeignKey(blank=True, db_column='ngaycapnhat', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tintuc.ngaythang')),
            ],
            options={
                'db_table': 'gialaivacine',
            },
        ),
        migrations.CreateModel(
            name='Gialaicovid',
            fields=[
                ('idcovid', models.AutoField(primary_key=True, serialize=False)),
                ('tongsoca', models.IntegerField(blank=True, null=True)),
                ('homnay', models.IntegerField(blank=True, null=True)),
                ('tuvong', models.IntegerField(blank=True, null=True)),
                ('ngaycapnhatcovid', models.ForeignKey(blank=True, db_column='ngaycapnhatcovid', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tintuc.ngaythang')),
            ],
            options={
                'db_table': 'gialaicovid',
            },
        ),
        migrations.CreateModel(
            name='Dongthapvacine',
            fields=[
                ('idvaccine', models.AutoField(primary_key=True, serialize=False)),
                ('khphanbo', models.IntegerField(blank=True, null=True)),
                ('phanbothucte', models.IntegerField(blank=True, null=True)),
                ('danso', models.IntegerField(blank=True, null=True)),
                ('solieudatiem', models.IntegerField(blank=True, null=True)),
                ('ngaycapnhat', models.ForeignKey(blank=True, db_column='ngaycapnhat', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tintuc.ngaythang')),
            ],
            options={
                'db_table': 'dongthapvacine',
            },
        ),
        migrations.CreateModel(
            name='Dongthapcovid',
            fields=[
                ('idcovid', models.AutoField(primary_key=True, serialize=False)),
                ('tongsoca', models.IntegerField(blank=True, null=True)),
                ('homnay', models.IntegerField(blank=True, null=True)),
                ('tuvong', models.IntegerField(blank=True, null=True)),
                ('ngaycapnhatcovid', models.ForeignKey(blank=True, db_column='ngaycapnhatcovid', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tintuc.ngaythang')),
            ],
            options={
                'db_table': 'dongthapcovid',
            },
        ),
        migrations.CreateModel(
            name='Dongnaivacine',
            fields=[
                ('idvaccine', models.AutoField(primary_key=True, serialize=False)),
                ('khphanbo', models.IntegerField(blank=True, null=True)),
                ('phanbothucte', models.IntegerField(blank=True, null=True)),
                ('danso', models.IntegerField(blank=True, null=True)),
                ('solieudatiem', models.IntegerField(blank=True, null=True)),
                ('ngaycapnhat', models.ForeignKey(blank=True, db_column='ngaycapnhat', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tintuc.ngaythang')),
            ],
            options={
                'db_table': 'dongnaivacine',
            },
        ),
        migrations.CreateModel(
            name='Dongnaicovid',
            fields=[
                ('idcovid', models.AutoField(primary_key=True, serialize=False)),
                ('tongsoca', models.IntegerField(blank=True, null=True)),
                ('homnay', models.IntegerField(blank=True, null=True)),
                ('tuvong', models.IntegerField(blank=True, null=True)),
                ('ngaycapnhatcovid', models.ForeignKey(blank=True, db_column='ngaycapnhatcovid', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tintuc.ngaythang')),
            ],
            options={
                'db_table': 'dongnaicovid',
            },
        ),
        migrations.CreateModel(
            name='Dienbienvacine',
            fields=[
                ('idvaccine', models.AutoField(primary_key=True, serialize=False)),
                ('khphanbo', models.IntegerField(blank=True, null=True)),
                ('phanbothucte', models.IntegerField(blank=True, null=True)),
                ('danso', models.IntegerField(blank=True, null=True)),
                ('solieudatiem', models.IntegerField(blank=True, null=True)),
                ('ngaycapnhat', models.ForeignKey(blank=True, db_column='ngaycapnhat', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tintuc.ngaythang')),
            ],
            options={
                'db_table': 'dienbienvacine',
            },
        ),
        migrations.CreateModel(
            name='Dienbiencovid',
            fields=[
                ('idcovid', models.AutoField(primary_key=True, serialize=False)),
                ('tongsoca', models.IntegerField(blank=True, null=True)),
                ('homnay', models.IntegerField(blank=True, null=True)),
                ('tuvong', models.IntegerField(blank=True, null=True)),
                ('ngaycapnhatcovid', models.ForeignKey(blank=True, db_column='ngaycapnhatcovid', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tintuc.ngaythang')),
            ],
            options={
                'db_table': 'dienbiencovid',
            },
        ),
        migrations.CreateModel(
            name='Danangvacine',
            fields=[
                ('idvaccine', models.AutoField(primary_key=True, serialize=False)),
                ('khphanbo', models.IntegerField(blank=True, null=True)),
                ('phanbothucte', models.IntegerField(blank=True, null=True)),
                ('danso', models.IntegerField(blank=True, null=True)),
                ('solieudatiem', models.IntegerField(blank=True, null=True)),
                ('ngaycapnhat', models.ForeignKey(blank=True, db_column='ngaycapnhat', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tintuc.ngaythang')),
            ],
            options={
                'db_table': 'danangvacine',
            },
        ),
        migrations.CreateModel(
            name='Danangcovid',
            fields=[
                ('idcovid', models.AutoField(primary_key=True, serialize=False)),
                ('tongsoca', models.IntegerField(blank=True, null=True)),
                ('homnay', models.IntegerField(blank=True, null=True)),
                ('tuvong', models.IntegerField(blank=True, null=True)),
                ('ngaycapnhatcovid', models.ForeignKey(blank=True, db_column='ngaycapnhatcovid', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tintuc.ngaythang')),
            ],
            options={
                'db_table': 'danangcovid',
            },
        ),
        migrations.CreateModel(
            name='Daknongvacine',
            fields=[
                ('idvaccine', models.AutoField(primary_key=True, serialize=False)),
                ('khphanbo', models.IntegerField(blank=True, null=True)),
                ('phanbothucte', models.IntegerField(blank=True, null=True)),
                ('danso', models.IntegerField(blank=True, null=True)),
                ('solieudatiem', models.IntegerField(blank=True, null=True)),
                ('ngaycapnhat', models.ForeignKey(blank=True, db_column='ngaycapnhat', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tintuc.ngaythang')),
            ],
            options={
                'db_table': 'daknongvacine',
            },
        ),
        migrations.CreateModel(
            name='Daknongcovid',
            fields=[
                ('idcovid', models.AutoField(primary_key=True, serialize=False)),
                ('tongsoca', models.IntegerField(blank=True, null=True)),
                ('homnay', models.IntegerField(blank=True, null=True)),
                ('tuvong', models.IntegerField(blank=True, null=True)),
                ('ngaycapnhatcovid', models.ForeignKey(blank=True, db_column='ngaycapnhatcovid', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tintuc.ngaythang')),
            ],
            options={
                'db_table': 'daknongcovid',
            },
        ),
        migrations.CreateModel(
            name='Daklakvacine',
            fields=[
                ('idvaccine', models.AutoField(primary_key=True, serialize=False)),
                ('khphanbo', models.IntegerField(blank=True, null=True)),
                ('phanbothucte', models.IntegerField(blank=True, null=True)),
                ('danso', models.IntegerField(blank=True, null=True)),
                ('solieudatiem', models.IntegerField(blank=True, null=True)),
                ('ngaycapnhat', models.ForeignKey(blank=True, db_column='ngaycapnhat', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tintuc.ngaythang')),
            ],
            options={
                'db_table': 'daklakvacine',
            },
        ),
        migrations.CreateModel(
            name='Daklakcovid',
            fields=[
                ('idcovid', models.AutoField(primary_key=True, serialize=False)),
                ('tongsoca', models.IntegerField(blank=True, null=True)),
                ('homnay', models.IntegerField(blank=True, null=True)),
                ('tuvong', models.IntegerField(blank=True, null=True)),
                ('ngaycapnhatcovid', models.ForeignKey(blank=True, db_column='ngaycapnhatcovid', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tintuc.ngaythang')),
            ],
            options={
                'db_table': 'daklakcovid',
            },
        ),
        migrations.CreateModel(
            name='Caobangvacine',
            fields=[
                ('idvaccine', models.AutoField(primary_key=True, serialize=False)),
                ('khphanbo', models.IntegerField(blank=True, null=True)),
                ('phanbothucte', models.IntegerField(blank=True, null=True)),
                ('danso', models.IntegerField(blank=True, null=True)),
                ('solieudatiem', models.IntegerField(blank=True, null=True)),
                ('ngaycapnhat', models.ForeignKey(blank=True, db_column='ngaycapnhat', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tintuc.ngaythang')),
            ],
            options={
                'db_table': 'caobangvacine',
            },
        ),
        migrations.CreateModel(
            name='Caobangcovid',
            fields=[
                ('idcovid', models.AutoField(primary_key=True, serialize=False)),
                ('tongsoca', models.IntegerField(blank=True, null=True)),
                ('homnay', models.IntegerField(blank=True, null=True)),
                ('tuvong', models.IntegerField(blank=True, null=True)),
                ('ngaycapnhatcovid', models.ForeignKey(blank=True, db_column='ngaycapnhatcovid', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tintuc.ngaythang')),
            ],
            options={
                'db_table': 'caobangcovid',
            },
        ),
        migrations.CreateModel(
            name='Canthovacine',
            fields=[
                ('idvaccine', models.AutoField(primary_key=True, serialize=False)),
                ('khphanbo', models.IntegerField(blank=True, null=True)),
                ('phanbothucte', models.IntegerField(blank=True, null=True)),
                ('danso', models.IntegerField(blank=True, null=True)),
                ('solieudatiem', models.IntegerField(blank=True, null=True)),
                ('ngaycapnhat', models.ForeignKey(blank=True, db_column='ngaycapnhat', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tintuc.ngaythang')),
            ],
            options={
                'db_table': 'canthovacine',
            },
        ),
        migrations.CreateModel(
            name='Canthocovid',
            fields=[
                ('idcovid', models.AutoField(primary_key=True, serialize=False)),
                ('tongsoca', models.IntegerField(blank=True, null=True)),
                ('homnay', models.IntegerField(blank=True, null=True)),
                ('tuvong', models.IntegerField(blank=True, null=True)),
                ('ngaycapnhatcovid', models.ForeignKey(blank=True, db_column='ngaycapnhatcovid', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tintuc.ngaythang')),
            ],
            options={
                'db_table': 'canthocovid',
            },
        ),
        migrations.CreateModel(
            name='Camauvacine',
            fields=[
                ('idvaccine', models.AutoField(primary_key=True, serialize=False)),
                ('khphanbo', models.IntegerField(blank=True, null=True)),
                ('phanbothucte', models.IntegerField(blank=True, null=True)),
                ('danso', models.IntegerField(blank=True, null=True)),
                ('solieudatiem', models.IntegerField(blank=True, null=True)),
                ('ngaycapnhat', models.ForeignKey(blank=True, db_column='ngaycapnhat', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tintuc.ngaythang')),
            ],
            options={
                'db_table': 'camauvacine',
            },
        ),
        migrations.CreateModel(
            name='Camaucovid',
            fields=[
                ('idcovid', models.AutoField(primary_key=True, serialize=False)),
                ('tongsoca', models.IntegerField(blank=True, null=True)),
                ('homnay', models.IntegerField(blank=True, null=True)),
                ('tuvong', models.IntegerField(blank=True, null=True)),
                ('ngaycapnhatcovid', models.ForeignKey(blank=True, db_column='ngaycapnhatcovid', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tintuc.ngaythang')),
            ],
            options={
                'db_table': 'camaucovid',
            },
        ),
        migrations.CreateModel(
            name='Binhthuanvacine',
            fields=[
                ('idvaccine', models.AutoField(primary_key=True, serialize=False)),
                ('khphanbo', models.IntegerField(blank=True, null=True)),
                ('phanbothucte', models.IntegerField(blank=True, null=True)),
                ('danso', models.IntegerField(blank=True, null=True)),
                ('solieudatiem', models.IntegerField(blank=True, null=True)),
                ('ngaycapnhat', models.ForeignKey(blank=True, db_column='ngaycapnhat', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tintuc.ngaythang')),
            ],
            options={
                'db_table': 'binhthuanvacine',
            },
        ),
        migrations.CreateModel(
            name='Binhthuancovid',
            fields=[
                ('idcovid', models.AutoField(primary_key=True, serialize=False)),
                ('tongsoca', models.IntegerField(blank=True, null=True)),
                ('homnay', models.IntegerField(blank=True, null=True)),
                ('tuvong', models.IntegerField(blank=True, null=True)),
                ('ngaycapnhatcovid', models.ForeignKey(blank=True, db_column='ngaycapnhatcovid', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tintuc.ngaythang')),
            ],
            options={
                'db_table': 'binhthuancovid',
            },
        ),
        migrations.CreateModel(
            name='Binhphuocvacine',
            fields=[
                ('idvaccine', models.AutoField(primary_key=True, serialize=False)),
                ('khphanbo', models.IntegerField(blank=True, null=True)),
                ('phanbothucte', models.IntegerField(blank=True, null=True)),
                ('danso', models.IntegerField(blank=True, null=True)),
                ('solieudatiem', models.IntegerField(blank=True, null=True)),
                ('ngaycapnhat', models.ForeignKey(blank=True, db_column='ngaycapnhat', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tintuc.ngaythang')),
            ],
            options={
                'db_table': 'binhphuocvacine',
            },
        ),
        migrations.CreateModel(
            name='Binhphuoccovid',
            fields=[
                ('idcovid', models.AutoField(primary_key=True, serialize=False)),
                ('tongsoca', models.IntegerField(blank=True, null=True)),
                ('homnay', models.IntegerField(blank=True, null=True)),
                ('tuvong', models.IntegerField(blank=True, null=True)),
                ('ngaycapnhatcovid', models.ForeignKey(blank=True, db_column='ngaycapnhatcovid', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tintuc.ngaythang')),
            ],
            options={
                'db_table': 'binhphuoccovid',
            },
        ),
        migrations.CreateModel(
            name='Binhduongvacine',
            fields=[
                ('idvaccine', models.AutoField(primary_key=True, serialize=False)),
                ('khphanbo', models.IntegerField(blank=True, null=True)),
                ('phanbothucte', models.IntegerField(blank=True, null=True)),
                ('danso', models.IntegerField(blank=True, null=True)),
                ('solieudatiem', models.IntegerField(blank=True, null=True)),
                ('ngaycapnhat', models.ForeignKey(blank=True, db_column='ngaycapnhat', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tintuc.ngaythang')),
            ],
            options={
                'db_table': 'binhduongvacine',
            },
        ),
        migrations.CreateModel(
            name='Binhduongcovid',
            fields=[
                ('idcovid', models.AutoField(primary_key=True, serialize=False)),
                ('tongsoca', models.IntegerField(blank=True, null=True)),
                ('homnay', models.IntegerField(blank=True, null=True)),
                ('tuvong', models.IntegerField(blank=True, null=True)),
                ('ngaycapnhatcovid', models.ForeignKey(blank=True, db_column='ngaycapnhatcovid', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tintuc.ngaythang')),
            ],
            options={
                'db_table': 'binhduongcovid',
            },
        ),
        migrations.CreateModel(
            name='Binhdinhvacine',
            fields=[
                ('idvaccine', models.AutoField(primary_key=True, serialize=False)),
                ('khphanbo', models.IntegerField(blank=True, null=True)),
                ('phanbothucte', models.IntegerField(blank=True, null=True)),
                ('danso', models.IntegerField(blank=True, null=True)),
                ('solieudatiem', models.IntegerField(blank=True, null=True)),
                ('ngaycapnhat', models.ForeignKey(blank=True, db_column='ngaycapnhat', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tintuc.ngaythang')),
            ],
            options={
                'db_table': 'binhdinhvacine',
            },
        ),
        migrations.CreateModel(
            name='Binhdinhcovid',
            fields=[
                ('idcovid', models.AutoField(primary_key=True, serialize=False)),
                ('tongsoca', models.IntegerField(blank=True, null=True)),
                ('homnay', models.IntegerField(blank=True, null=True)),
                ('tuvong', models.IntegerField(blank=True, null=True)),
                ('ngaycapnhatcovid', models.ForeignKey(blank=True, db_column='ngaycapnhatcovid', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tintuc.ngaythang')),
            ],
            options={
                'db_table': 'binhdinhcovid',
            },
        ),
        migrations.CreateModel(
            name='Bentrevacine',
            fields=[
                ('idvaccine', models.AutoField(primary_key=True, serialize=False)),
                ('khphanbo', models.IntegerField(blank=True, null=True)),
                ('phanbothucte', models.IntegerField(blank=True, null=True)),
                ('danso', models.IntegerField(blank=True, null=True)),
                ('solieudatiem', models.IntegerField(blank=True, null=True)),
                ('ngaycapnhat', models.ForeignKey(blank=True, db_column='ngaycapnhat', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tintuc.ngaythang')),
            ],
            options={
                'db_table': 'bentrevacine',
            },
        ),
        migrations.CreateModel(
            name='Bentrecovid',
            fields=[
                ('idcovid', models.AutoField(primary_key=True, serialize=False)),
                ('tongsoca', models.IntegerField(blank=True, null=True)),
                ('homnay', models.IntegerField(blank=True, null=True)),
                ('tuvong', models.IntegerField(blank=True, null=True)),
                ('ngaycapnhatcovid', models.ForeignKey(blank=True, db_column='ngaycapnhatcovid', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tintuc.ngaythang')),
            ],
            options={
                'db_table': 'bentrecovid',
            },
        ),
        migrations.CreateModel(
            name='Bariavungtauvacine',
            fields=[
                ('idvaccine', models.AutoField(primary_key=True, serialize=False)),
                ('khphanbo', models.IntegerField(blank=True, null=True)),
                ('phanbothucte', models.IntegerField(blank=True, null=True)),
                ('danso', models.IntegerField(blank=True, null=True)),
                ('solieudatiem', models.IntegerField(blank=True, null=True)),
                ('ngaycapnhat', models.ForeignKey(blank=True, db_column='ngaycapnhat', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tintuc.ngaythang')),
            ],
            options={
                'db_table': 'bariavungtauvacine',
            },
        ),
        migrations.CreateModel(
            name='Bariavungtaucovid',
            fields=[
                ('idcovid', models.AutoField(primary_key=True, serialize=False)),
                ('tongsoca', models.IntegerField(blank=True, null=True)),
                ('homnay', models.IntegerField(blank=True, null=True)),
                ('tuvong', models.IntegerField(blank=True, null=True)),
                ('ngaycapnhatcovid', models.ForeignKey(blank=True, db_column='ngaycapnhatcovid', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tintuc.ngaythang')),
            ],
            options={
                'db_table': 'bariavungtaucovid',
            },
        ),
        migrations.CreateModel(
            name='Bacningvacine',
            fields=[
                ('idvaccine', models.AutoField(primary_key=True, serialize=False)),
                ('khphanbo', models.IntegerField(blank=True, null=True)),
                ('phanbothucte', models.IntegerField(blank=True, null=True)),
                ('danso', models.IntegerField(blank=True, null=True)),
                ('solieudatiem', models.IntegerField(blank=True, null=True)),
                ('ngaycapnhat', models.ForeignKey(blank=True, db_column='ngaycapnhat', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tintuc.ngaythang')),
            ],
            options={
                'db_table': 'bacningvacine',
            },
        ),
        migrations.CreateModel(
            name='Bacningcovid',
            fields=[
                ('idcovid', models.AutoField(primary_key=True, serialize=False)),
                ('tongsoca', models.IntegerField(blank=True, null=True)),
                ('homnay', models.IntegerField(blank=True, null=True)),
                ('tuvong', models.IntegerField(blank=True, null=True)),
                ('ngaycapnhatcovid', models.ForeignKey(blank=True, db_column='ngaycapnhatcovid', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tintuc.ngaythang')),
            ],
            options={
                'db_table': 'bacningcovid',
            },
        ),
        migrations.CreateModel(
            name='Baclieuvacine',
            fields=[
                ('idvaccine', models.AutoField(primary_key=True, serialize=False)),
                ('khphanbo', models.IntegerField(blank=True, null=True)),
                ('phanbothucte', models.IntegerField(blank=True, null=True)),
                ('danso', models.IntegerField(blank=True, null=True)),
                ('solieudatiem', models.IntegerField(blank=True, null=True)),
                ('ngaycapnhat', models.ForeignKey(blank=True, db_column='ngaycapnhat', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tintuc.ngaythang')),
            ],
            options={
                'db_table': 'baclieuvacine',
            },
        ),
        migrations.CreateModel(
            name='Baclieucovid',
            fields=[
                ('idcovid', models.AutoField(primary_key=True, serialize=False)),
                ('tongsoca', models.IntegerField(blank=True, null=True)),
                ('homnay', models.IntegerField(blank=True, null=True)),
                ('tuvong', models.IntegerField(blank=True, null=True)),
                ('ngaycapnhatcovid', models.ForeignKey(blank=True, db_column='ngaycapnhatcovid', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tintuc.ngaythang')),
            ],
            options={
                'db_table': 'baclieucovid',
            },
        ),
        migrations.CreateModel(
            name='Backanvacine',
            fields=[
                ('idvaccine', models.AutoField(primary_key=True, serialize=False)),
                ('khphanbo', models.IntegerField(blank=True, null=True)),
                ('phanbothucte', models.IntegerField(blank=True, null=True)),
                ('danso', models.IntegerField(blank=True, null=True)),
                ('solieudatiem', models.IntegerField(blank=True, null=True)),
                ('ngaycapnhat', models.ForeignKey(blank=True, db_column='ngaycapnhat', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tintuc.ngaythang')),
            ],
            options={
                'db_table': 'backanvacine',
            },
        ),
        migrations.CreateModel(
            name='Backancovid',
            fields=[
                ('idcovid', models.AutoField(primary_key=True, serialize=False)),
                ('tongsoca', models.IntegerField(blank=True, null=True)),
                ('homnay', models.IntegerField(blank=True, null=True)),
                ('tuvong', models.IntegerField(blank=True, null=True)),
                ('ngaycapnhatcovid', models.ForeignKey(blank=True, db_column='ngaycapnhatcovid', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tintuc.ngaythang')),
            ],
            options={
                'db_table': 'backancovid',
            },
        ),
        migrations.CreateModel(
            name='Bacgiangvacine',
            fields=[
                ('idvaccine', models.AutoField(primary_key=True, serialize=False)),
                ('khphanbo', models.IntegerField(blank=True, null=True)),
                ('phanbothucte', models.IntegerField(blank=True, null=True)),
                ('danso', models.IntegerField(blank=True, null=True)),
                ('solieudatiem', models.IntegerField(blank=True, null=True)),
                ('ngaycapnhat', models.ForeignKey(blank=True, db_column='ngaycapnhat', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tintuc.ngaythang')),
            ],
            options={
                'db_table': 'bacgiangvacine',
            },
        ),
        migrations.CreateModel(
            name='Bacgiangcovid',
            fields=[
                ('idcovid', models.AutoField(primary_key=True, serialize=False)),
                ('tongsoca', models.IntegerField(blank=True, null=True)),
                ('homnay', models.IntegerField(blank=True, null=True)),
                ('tuvong', models.IntegerField(blank=True, null=True)),
                ('ngaycapnhatcovid', models.ForeignKey(blank=True, db_column='ngaycapnhatcovid', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tintuc.ngaythang')),
            ],
            options={
                'db_table': 'bacgiangcovid',
            },
        ),
        migrations.CreateModel(
            name='Angiangvacine',
            fields=[
                ('idvaccine', models.AutoField(primary_key=True, serialize=False)),
                ('khphanbo', models.IntegerField(blank=True, null=True)),
                ('phanbothucte', models.IntegerField(blank=True, null=True)),
                ('danso', models.IntegerField(blank=True, null=True)),
                ('solieudatiem', models.IntegerField(blank=True, null=True)),
                ('ngaycapnhat', models.ForeignKey(blank=True, db_column='ngaycapnhat', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tintuc.ngaythang')),
            ],
            options={
                'db_table': 'angiangvacine',
            },
        ),
        migrations.CreateModel(
            name='Angiangcovid',
            fields=[
                ('idcovid', models.AutoField(primary_key=True, serialize=False)),
                ('tongsoca', models.IntegerField(blank=True, null=True)),
                ('homnay', models.IntegerField(blank=True, null=True)),
                ('tuvong', models.IntegerField(blank=True, null=True)),
                ('ngaycapnhatcovid', models.ForeignKey(blank=True, db_column='ngaycapnhatcovid', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tintuc.ngaythang')),
            ],
            options={
                'db_table': 'angiangcovid',
            },
        ),
    ]
