# Generated by Django 3.2.8 on 2021-11-07 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('thongke', '0003_dienbiendich'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tinhthanh',
            fields=[
                ('idtinhthanh', models.AutoField(primary_key=True, serialize=False)),
                ('tentinhthanh', models.CharField(blank=True, max_length=50, null=True, unique=True)),
            ],
            options={
                'db_table': 'tinhthanh',
            },
        ),
        migrations.CreateModel(
            name='Tinhhinhvaccine',
            fields=[
                ('idvaccine', models.AutoField(primary_key=True, serialize=False)),
                ('khphanbo', models.IntegerField(blank=True, null=True)),
                ('phanbothucte', models.IntegerField(blank=True, null=True)),
                ('danso', models.IntegerField(blank=True, null=True)),
                ('solieudatiem', models.IntegerField(blank=True, null=True)),
                ('ngaycapnhat', models.ForeignKey(blank=True, db_column='ngaycapnhat', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='thongke.ngaythang', to_field='ngaythang')),
                ('tentinhthanh', models.ForeignKey(blank=True, db_column='tentinhthanh', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='thongke.tinhthanh', to_field='tentinhthanh')),
            ],
            options={
                'db_table': 'tinhhinhvaccine',
            },
        ),
    ]
