# Generated by Django 3.2.8 on 2021-11-09 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thongke', '0006_diemtiemchung_quanhuyen'),
    ]

    operations = [
        migrations.AddField(
            model_name='dienbiendich',
            name='tieude',
            field=models.CharField(blank=True, db_column='tieude', max_length=100, null=True),
        ),
    ]
