# Generated by Django 3.2.8 on 2021-11-10 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('thongke', '0009_alter_tinhhinhcovid_homnay'),
    ]

    operations = [
        migrations.CreateModel(
            name='TinhhinhcovidVn',
            fields=[
                ('idcovid', models.AutoField(primary_key=True, serialize=False)),
                ('tongsoca', models.IntegerField(blank=True, null=True)),
                ('homnay', models.CharField(blank=True, max_length=7, null=True)),
                ('tuvong', models.IntegerField(blank=True, null=True)),
                ('ngaycapnhat', models.ForeignKey(blank=True, db_column='ngaycapnhat', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='thongke.ngaythang', to_field='ngaythang')),
            ],
            options={
                'db_table': 'tinhhinhcovid_vn',
            },
        ),
        migrations.CreateModel(
            name='TinhhinhcovidTg',
            fields=[
                ('idcovid', models.AutoField(primary_key=True, serialize=False)),
                ('tongsoca', models.IntegerField(blank=True, null=True)),
                ('homnay', models.CharField(blank=True, max_length=7, null=True)),
                ('tuvong', models.IntegerField(blank=True, null=True)),
                ('ngaycapnhat', models.ForeignKey(blank=True, db_column='ngaycapnhat', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='thongke.ngaythang', to_field='ngaythang')),
            ],
            options={
                'db_table': 'tinhhinhcovid_tg',
            },
        ),
    ]
