# Generated by Django 3.2.8 on 2021-11-10 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thongke', '0010_tinhhinhcovidtg_tinhhinhcovidvn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tinhhinhcovidtg',
            name='homnay',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tinhhinhcovidvn',
            name='homnay',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
