# Generated by Django 3.2.8 on 2021-11-14 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('thongke', '0011_auto_20211110_1525'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tinhhinhcovidtg',
            old_name='homnay',
            new_name='khoi',
        ),
        migrations.RenameField(
            model_name='tinhhinhcovidvn',
            old_name='homnay',
            new_name='khoi',
        ),
    ]
