# Generated by Django 3.2.8 on 2021-11-14 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thongke', '0012_auto_20211114_0930'),
    ]

    operations = [
        migrations.CreateModel(
            name='ngaycapnhat',
            fields=[
                ('idngay', models.AutoField(primary_key=True, serialize=False)),
                ('ngaythang', models.DateField(blank=True, null=True, unique=True)),
            ],
            options={
                'db_table': 'ngaycapnhat',
            },
        ),
    ]
