# Generated by Django 3.2.8 on 2021-11-14 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thongke', '0013_ngaycapnhat'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ngaycapnhat',
        ),
        migrations.AlterField(
            model_name='ngaythang',
            name='ngaythang',
            field=models.DateTimeField(blank=True, null=True, unique=True),
        ),
    ]
