# Generated by Django 3.2.8 on 2021-11-15 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thongke', '0014_auto_20211114_1100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ngaythang',
            name='ngaythang',
            field=models.DateField(blank=True, null=True, unique=True),
        ),
    ]
