# Generated by Django 3.2.8 on 2021-11-15 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thongke', '0015_alter_ngaythang_ngaythang'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ngaythang',
            name='ngaythang',
            field=models.DateTimeField(blank=True, null=True, unique=True),
        ),
    ]
