# Generated by Django 3.2.8 on 2021-11-02 02:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ngaythang',
            fields=[
                ('idngay', models.AutoField(primary_key=True, serialize=False)),
                ('ngay', models.DateTimeField()),
            ],
            options={
                'db_table': 'ngaythang',
            },
        ),
        migrations.CreateModel(
            name='Baiviet',
            fields=[
                ('idbaiviet', models.AutoField(primary_key=True, serialize=False)),
                ('tenbaiviet', models.CharField(db_column='tenBaiviet', max_length=30)),
                ('chudebaiviet', models.CharField(db_column='chuDeBaiViet', max_length=30)),
                ('noidungbaiviet', models.CharField(db_column='noiDungBaiviet', max_length=500)),
                ('hinhanh', models.CharField(blank=True, db_column='hinhAnh', max_length=50, null=True)),
                ('binhluan', models.CharField(blank=True, db_column='binhLuan', max_length=200, null=True)),
                ('ngaydangbaiviet', models.ForeignKey(blank=True, db_column='ngayDangBaiViet', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tintuc.ngaythang')),
            ],
            options={
                'db_table': 'baiviet',
            },
        ),
    ]
