# Generated by Django 3.2.8 on 2021-11-02 02:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tintuc', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baiviet',
            name='ngaydangbaiviet',
            field=models.ForeignKey(blank=True, db_column='ngayDangBaiViet', null=True, on_delete=django.db.models.deletion.CASCADE, to='tintuc.ngaythang'),
        ),
    ]
