# Generated by Django 3.2.8 on 2021-11-06 01:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tintuc', '0003_auto_20211106_0806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baiviet',
            name='ngaydangbaiviet',
            field=models.ForeignKey(blank=True, db_column='ngayDangBaiViet', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tintuc.ngaygio', to_field='ngaygio'),
        ),
    ]
