# Generated by Django 3.2.8 on 2021-11-06 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tintuc', '0004_alter_baiviet_ngaydangbaiviet'),
    ]

    operations = [
        migrations.AddField(
            model_name='baiviet',
            name='tacgia',
            field=models.CharField(blank=True, db_column='tacgia', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='baiviet',
            name='ngaydangbaiviet',
            field=models.ForeignKey(blank=True, db_column='ngayDangBaiViet', null=True, on_delete=django.db.models.deletion.CASCADE, to='tintuc.ngaygio', to_field='ngaygio'),
        ),
        migrations.AlterField(
            model_name='baiviet',
            name='noidungbaiviet',
            field=models.TextField(db_column='noiDungBaiviet', max_length=500),
        ),
    ]
