# Generated by Django 3.2.8 on 2021-11-07 08:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tintuc', '0005_auto_20211106_0943'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chudebaiviet',
            fields=[
                ('idchudebaiviet', models.AutoField(primary_key=True, serialize=False)),
                ('chude', models.CharField(blank=True, max_length=50, null=True, unique=True)),
            ],
            options={
                'db_table': 'chudebaiviet',
            },
        ),
        migrations.AlterField(
            model_name='baiviet',
            name='binhluan',
            field=models.CharField(blank=True, db_column='binhLuan', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='baiviet',
            name='hinhanh',
            field=models.CharField(blank=True, db_column='hinhAnh', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='baiviet',
            name='noidungbaiviet',
            field=models.TextField(db_column='noiDungBaiviet'),
        ),
        migrations.AlterField(
            model_name='baiviet',
            name='tenbaiviet',
            field=models.CharField(db_column='tenBaiviet', max_length=500),
        ),
        migrations.AlterField(
            model_name='baiviet',
            name='chudebaiviet',
            field=models.ForeignKey(blank=True, db_column='chuDeBaiViet', null=True, on_delete=django.db.models.deletion.CASCADE, to='tintuc.chudebaiviet', to_field='chude'),
        ),
    ]
