# Generated by Django 3.2.8 on 2021-11-07 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tintuc', '0006_auto_20211107_0801'),
    ]

    operations = [
        migrations.AddField(
            model_name='baiviet',
            name='tomtat',
            field=models.TextField(db_column='tomtat', default='SOME STRING'),
        ),
    ]
