# Generated by Django 3.2.8 on 2021-11-07 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tintuc', '0007_baiviet_tomtat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chudebaiviet',
            name='chude',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='baiviet',
            unique_together={('chudebaiviet',)},
        ),
        migrations.AlterUniqueTogether(
            name='chudebaiviet',
            unique_together={('chude',)},
        ),
    ]
