# Generated by Django 3.2.8 on 2021-11-07 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tintuc', '0008_auto_20211107_0854'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='baiviet',
            options={'managed': False},
        ),
    ]
