# Generated by Django 3.2.8 on 2021-11-07 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tintuc', '0009_alter_baiviet_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chudebaiviet',
            name='chude',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='chudebaiviet',
            unique_together=set(),
        ),
    ]
