# Generated by Django 3.2.8 on 2021-11-07 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tintuc', '0010_auto_20211107_0928'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='baiviet',
            options={},
        ),
    ]
