# Generated by Django 3.2.8 on 2021-11-07 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tintuc', '0011_alter_baiviet_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baiviet',
            name='chudebaiviet',
            field=models.ForeignKey(db_column='chuDeBaiViet', on_delete=django.db.models.deletion.DO_NOTHING, to='tintuc.chudebaiviet', to_field='chude'),
        ),
        migrations.AlterField(
            model_name='baiviet',
            name='ngaydangbaiviet',
            field=models.ForeignKey(blank=True, db_column='ngayDangBaiViet', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tintuc.ngaygio', to_field='ngaygio'),
        ),
        migrations.AlterField(
            model_name='baiviet',
            name='tacgia',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='baiviet',
            name='tomtat',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='baiviet',
            unique_together=set(),
        ),
    ]
