# Generated by Django 3.2.8 on 2021-11-14 09:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tintuc', '0012_auto_20211107_1019'),
    ]

    operations = [
        migrations.CreateModel(
            name='Binhluan',
            fields=[
                ('idbinhluan', models.AutoField(primary_key=True, serialize=False)),
                ('noidungbinhluan', models.TextField(blank=True, null=True)),
                ('baiviet', models.ForeignKey(blank=True, db_column='baiviet', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='tintuc.baiviet')),
                ('ngaydangbinhluan', models.ForeignKey(blank=True, db_column='ngaydangbinhluan', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tintuc.ngaygio', to_field='ngaygio')),
                ('taikhoan', models.ForeignKey(blank=True, db_column='taikhoan', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'binhluan',
            },
        ),
    ]
