# Generated by Django 3.2.8 on 2021-11-14 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tintuc', '0013_binhluan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ngaygio',
            name='ngaygio',
            field=models.DateTimeField(auto_now_add=True, null=True, unique=True),
        ),
    ]
