# Generated by Django 3.2.8 on 2021-11-15 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tintuc', '0016_alter_ngaygio_ngaygio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='baiviet',
            name='binhluan',
        ),
        migrations.AlterField(
            model_name='binhluan',
            name='baiviet',
            field=models.ForeignKey(blank=True, db_column='baiviet', null=True, on_delete=django.db.models.deletion.CASCADE, to='tintuc.baiviet'),
        ),
        migrations.AlterField(
            model_name='binhluan',
            name='noidungbinhluan',
            field=models.TextField(null=True),
        ),
    ]
