# Generated by Django 3.2.8 on 2021-11-21 08:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tintuc', '0018_auto_20211121_0836'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='binhluan',
            options={},
        ),
        migrations.RemoveField(
            model_name='binhluan',
            name='active',
        ),
        migrations.AlterField(
            model_name='binhluan',
            name='baiviet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='tintuc.baiviet'),
        ),
        migrations.AlterField(
            model_name='binhluan',
            name='noidungbinhluan',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='binhluan',
            name='taikhoan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
        ),
    ]
