# Generated by Django 3.2.8 on 2021-11-21 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tintuc', '0019_auto_20211121_0854'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='binhluan',
            table='binhluan',
        ),
    ]
