# Generated by Django 3.2.8 on 2021-11-21 09:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tintuc', '0020_alter_binhluan_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='binhluan',
            name='ngaydang',
        ),
        migrations.AddField(
            model_name='binhluan',
            name='ngaydangbinhluan',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='binhluan',
            name='baiviet',
            field=models.ForeignKey(blank=True, db_column='baiviet', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tintuc.baiviet'),
        ),
        migrations.AlterField(
            model_name='binhluan',
            name='taikhoan',
            field=models.ForeignKey(blank=True, db_column='taikhoan', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
