# Generated by Django 3.2.8 on 2021-11-21 09:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tintuc', '0021_auto_20211121_0904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='binhluan',
            name='baiviet',
            field=models.ForeignKey(blank=True, db_column='baiviet', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='comments', to='tintuc.baiviet'),
        ),
    ]
